apiVersion: v1
kind: Namespace
metadata:
  name: report
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: report
  namespace: report
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-reader-cr
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["namespaces", "services", "deployments","pods","daemonsets", "replicasets", "statefulsets","jobs", "cronjobs" ]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ns-reader-cr
subjects:
- kind: ServiceAccount
  name: report
  namespace: report
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-report
  namespace: report
spec:
  template:
    metadata:
    spec:
      serviceAccountName: report
      containers:
        - name: k8s-report
          image: mavridis/go-client-report
          imagePullPolicy: IfNotPresent
          env:
          - name: K8S_NAMESPACE
            value: "kube-system"
          args: [$(K8S_NAMESPACE)]        
          securityContext:
            runAsUser: 12222 
            allowPrivilegeEscalation: false     
      restartPolicy: Never